# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Download"
  url = "#download"
  weight = 10

[[main]]
  name = "Documentation"
  url = "#documentation"
  weight = 20

[[main]]
  name = "Related projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Papers"
  weight = 40

[[main]]
  parent = "Papers"
  name = "Papers citing PR2"
  url = "papers/papers-citing-pr2"
  weight = 1

[[main]]
  name = "About"
  weight = 60

[[main]]
  parent = "About"
  name = "Contact"
  url = "#contact"
  weight = 2
  
[[main]]
  parent = "About"
  name = "Team"
  url = "#people"
  weight = 1

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
