# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Download"
  url = "#download"
  weight = 10

[[main]]
  name = "Documentation"
  url = "documentation"
  weight = 20

[[main]]
    name = "Annotation"
    weight = 30

[[main]]
  parent = "Annotation"
  name = "Groups annotated"
  url = "/documentation/pr2-taxonomic-groups/"
  weight = 1

[[main]]
  parent = "Annotation"
  name = "Contributing"
  url = "#contributing"
  weight = 2

[[main]]
  parent = "Annotation"
  name = "EukRef"
  url = "/eukref/about"
  weight = 3

[[main]]
    name = "Workshops"
    weight = 35

[[main]]
  parent = "Workshops"
  name = "Workshop 2015"
  url = "eukref/workshop_vancouver"
  weight = 3

[[main]]
  parent = "Workshops"
  name = "Workshop 2016"
  url = "eukref/workshop_barcelona"
  weight = 4

[[main]]
  parent = "Workshops"
  name = "Workshop 2018"
  url = "eukref/workshop_roscoff"
  weight = 5

# [[main]]
#   name = "Related projects"
#   url = "#projects"
#   weight = 40

[[main]]
  name = "Papers"
  weight = 50

[[main]]
  parent = "Papers"
  name = "Papers citing PR2"
  url = "papers/papers-citing-pr2"
  weight = 1

[[main]]
  parent = "Papers"
  name = "Papers citing EukRef"
  url = "papers/papers-citing-eukref"
  weight = 2

[[main]]
  name = "News"
  url = "#news"
  weight = 60

# [[main]]
#   name = "Related projects"
#   url = "#projects"
#   weight = 70

[[main]]
  name = "About"
  weight = 5

[[main]]
  parent = "About"
  name = "About PR2"
  url = "#about"
  weight = 1

  [[main]]
    parent = "About"
    name = "Team"
    url = "team/"
    weight = 5

[[main]]
  parent = "About"
  name = "Funding"
  url = "#funding"
  weight = 7

[[main]]
  parent = "About"
  name = "Contact"
  url = "#contact"
  weight = 10


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
